#!/bin/sh
PWD=`pwd`
export ROOT_FS=$PWD/../rootfs-arm/
rm -f stapi.img
dd if=/dev/zero bs=512 count=4194304 of=stapi.img
/sbin/sfdisk stapi.img < stapi_img.layout
sudo /sbin/losetup -D
sudo /sbin/losetup -f -P stapi.img
sudo mkfs.fat /dev/loop0p1
sudo mkfs.ext4 /dev/loop0p2
sudo mkdir -f /mnt/dos
sudo mkdir -f /mnt/linux
sudo mount /dev/loop0p1 /mnt/dos
sudo mount /dev/loop0p2 /mnt/linux

